CREATE TABLE IF NOT EXISTS users (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(160) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('PRESIDENT','ASSISTANT_PRESIDENT','SECRETARY_GENERAL','TREASURER','AUDITOR','MEMBER') NOT NULL DEFAULT 'MEMBER',
  member_id VARCHAR(32) NOT NULL UNIQUE,
  total_savings DECIMAL(15,2) NOT NULL DEFAULT 0,
  join_date DATE NOT NULL,
  status ENUM('Active','Pending','Inactive') NOT NULL DEFAULT 'Pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sessions (
  id CHAR(64) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX sessions_expiry_idx (expires_at)
);

CREATE TABLE IF NOT EXISTS settings (
  id VARCHAR(32) PRIMARY KEY,
  settings_json JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id CHAR(36) PRIMARY KEY,
  action VARCHAR(160) NOT NULL,
  actor VARCHAR(160) NOT NULL,
  actor_role VARCHAR(40) NOT NULL,
  target VARCHAR(160) NOT NULL,
  status ENUM('VERIFIED','FLAGGED') NOT NULL DEFAULT 'VERIFIED',
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX audit_created_idx (created_at)
);

CREATE TABLE IF NOT EXISTS contributions (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  type ENUM('MONTHLY','SPECIAL','LEVY') NOT NULL,
  contribution_date DATE NOT NULL,
  status ENUM('SUCCESS','FAILED','PENDING') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT contributions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS loans (
  id CHAR(36) PRIMARY KEY,
  user_id CHAR(36) NOT NULL,
  member_name VARCHAR(160) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  loan_type_id VARCHAR(64) NOT NULL,
  status VARCHAR(64) NOT NULL,
  guarantors JSON NOT NULL,
  repayment_schedule JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT loans_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
